### ISSUE TITLE
[US 01.02.01] Create View Item Page

### ISSUE THREAD

**Issue by MatthewNeufeld** [CMPUT301F23T08/HouseHomey#10]
As an owner, I want to view an item and its details.

# Acceptance criteria
- Create "View Item Page" fragment that is accessible when user clicks on list item. Fragment should have the following attributes:
    - main photo of item
    - name of item
    - description of item
    - gallery of other photos of the item
    - Details of item:
        - make
        - model
        - serial number
        - est. cost (CAD)
    - tags related to the item
    - comment field
    - edit button that sends you to "Edit Item" fragment
    - don't worry about delete button: it will be implemented here: #16

# Unknowns
- should comment field be editable on this page?
- linking delete functionality to the list on home page

# Mockup
![Screen Shot 2023-10-19 at 22 03 32](https://github.com/CMPUT301F23T08/HouseHomey/assets/118775633/82e0eaa8-a5aa-4d22-bc1b-b1d665913a92)

**Comment by Vvvv77777** [comment]
@MatthewNeufeld Hi,can you please assign this issue to me,thanks!
