### ISSUE TITLE
[BUGFIX] Fix select button alignment

### ISSUE THREAD

**Issue by MatthewNeufeld** [CMPUT301F23T08/HouseHomey#101]
The select button isn't aligned with the list items or total value display.

Make it so that the select button is aligned with the list items and total value display.
![Screen Shot 2023-11-29 at 23 20 00](https://github.com/CMPUT301F23T08/HouseHomey/assets/118775633/f2f8339a-8e10-46cf-a5d8-b499f182e551)

**Comment by owencooke** [comment]
@MatthewNeufeld I'm going to create an issue for consolidating all the UI discrepancies into one branch that can be our final merge for the project. 

Closing this and moving it to the combined UI fixes issue https://github.com/CMPUT301F23T08/HouseHomey/issues/105
