### ISSUE TITLE
[US 03.02.01] View list of all tags 

### ISSUE THREAD

**Issue by antonio2uofa** [CMPUT301F23T08/HouseHomey#13]
As an owner, I want to specify one or more tags for an item.

# Acceptance criteria
- Add tag list to tag dialog fragment
- Tag list should be able to
    - display tags associated with current item
    - display total tags defined by user
    - update tags associated with current item
    - update when user defines a new tag

# Unknowns
- none

# Mockup
- Refer to: [TAGS - US 03.01.01](https://github.com/CMPUT301F23T08/HouseHomey/issues/8)

**Comment by MatthewNeufeld** [comment]
Closing because this task is within scope of https://github.com/CMPUT301F23T08/HouseHomey/issues/8
