### ISSUE TITLE
[US 01.04.01] Implement Item Deletion

### ISSUE THREAD

**Issue by MatthewNeufeld** [CMPUT301F23T08/HouseHomey#16]
As an owner, I want to delete an item.

This issue is for the deletion functionality component of the "View Item Page" in #10

# Acceptance criteria
- introduce delete button in "View Item Page", that when pressed, deletes item from item list
- ensure item is deleted in database as well as UI

# Unknowns
- Could be consistency complications regarding a single delete for this situation and a multi-delete from "Home Page"

# Mockup
![Screen Shot 2023-10-19 at 22 05 18](https://github.com/CMPUT301F23T08/HouseHomey/assets/118775633/197dfcb5-9bdc-4a53-be17-3189d1b0cd30)

**Comment by Vvvv77777** [comment]
@MatthewNeufeld Hi,can you please assign this issue to me,thanks!
