### ISSUE TITLE
LIST OF ITEMS - US 02.05.01, US 02.06.01, US 02.07.01

### ISSUE THREAD

**Issue by Sami-Jagirdar** [CMPUT301F23T08/HouseHomey#24]
As an owner, I want to filter the list of items by date range, description keywords or make (3 separate filtering options).

# Acceptance criteria
- There must be a "filter" button on the item list homepage which, on click,  pops up a dropdown fragment/menu with a list view of filtering options
  - Each filter option can be a clickable TextView. Clicking on any filter option pops up a dialog fragment specific to the selected filter option allowing the user to modify that filter
  - The required filter options are **date range**, **description keywords**, and **make of items**.

- The common views/elements on every filter's dialog fragment should be as follows:
  - An **Apply** button that applies the filter to the item list and displays all the filtered items on the homepage
  - A **Cancel** button that returns to the homepage without applying any filter
  - A **Reset** button that clears the input to the filter modifications

Following are the criteria for each specific modify filter dialog:
-**Modify Date range**
  - Must have 2 Date Picker views allowing the user to input the start date and end date respectively

-**Modify Make**
  - Must have an Edit Text view allowing the user to enter the make of the item (Alternatively, choose from a list of makes)

-**Modify Keyword**
 - Must have an Edit Text view allowing the user to enter a keyword from the descriptions of the items
 - Must have an "add" button that adds the entered keyword to a set of selected keywords
 - The keywords selected so far should be displayed on the dialog (perhaps as tags)

# Unknowns
- If multiple keywords or makes are selected, how will the filtered items be sorted and displayed.
- Choosing between an edit text for the make filter or choosing from a list of existing makes of the items in the user's list.
- If a filter has been added, how will we go about removing the filter (Perhaps have the option of resetting filters in the filter dropdown) 

# Mockup 
![image](https://github.com/CMPUT301F23T08/HouseHomey/assets/72996716/77b481e8-e3cb-4409-8d6a-cbc0e16a1a2e)
![image](https://github.com/CMPUT301F23T08/HouseHomey/assets/72996716/98a7ba4e-4ae1-4476-a4d2-c0b42b55c705)

**Comment by antonio2uofa** [comment]
Closed because it has been fully integrated
