### ISSUE TITLE
[SUBTASK] add reset to make filter

### ISSUE THREAD

**Issue by jdrco** [CMPUT301F23T08/HouseHomey#52]
As an owner, I should be able to reset the make filter I have selected

# Acceptance criteria
- Selected filter resets upon reset press
- Current make filter applied should be auto-filled when applying a new make filter.

**Comment by MatthewNeufeld** [comment]
@jdrco I'm not sure this constitutes to be a bug if it stems from a user story. I think this would be better labelled as a sub-task. Could do something like:

"[SUBTASK] add reset to make filter" and then link the parent story

If you disagree just lmk
